Examen2WebApp/Controllers/SolicitudController.cs
using Examen2WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Examen2WebApp.Controllers.Interfaces;

namespace Examen2WebApp.Controllers
{
    public class SolicitudController : Controller
    {
        private Examen2DatosEntities db = new Examen2DatosEntities();

        private ICalculoDonaciones servicioDonaciones = new CalculoDonaciones();

        public List<Docente> docentes;
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            docentes = db.Docentes.ToList();
            ViewBag.docentes = docentes;
        }

        // GET: Solicitud
        public ActionResult Index()
        {
            return View();
        }

        public void CalcularDonacionMentoria(Mentoria mentoria)
        {
            if (mentoria.Estado == "Aceptada" && (mentoria.Donacion == 0 || mentoria.Donacion == null))
            {
                mentoria.Donacion = servicioDonaciones.CalcularDonacion(mentoria.AreaDeMentoria.Nombre, mentoria.Docente.GradoAcademico, mentoria.Estudiante.Carrera, mentoria.Docente.Genero, mentoria.Estudiante.Genero);
                GuardarMentoria(mentoria);
            }
        }

        public void GuardarMentoria(Mentoria mentoria)
        {
            db.Entry(mentoria).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
        }

        public ActionResult RequestsList(string id)
        {
            
            List<Mentoria> mentorias = db.Mentorias.Where(m => m.CedulaDocente == id).ToList();
            if (mentorias == null)
            {
                return HttpNotFound();
            }
            foreach (var mentoria in mentorias)
            {
                CalcularDonacionMentoria(mentoria);
            }
            return View(mentorias);

        }

        public ActionResult AcceptRequest(string cedDoc, string cedEst, int areaId)
        {
            Mentoria mentoria = db.Mentorias.FirstOrDefault(m => m.CedulaDocente == cedDoc && cedEst == m.CedulaEstudiante && m.AreaDeMentoriaId == areaId);
            if (mentoria != null)
            {
                mentoria.Estado = "Aceptada";
                GuardarMentoria(mentoria);
            }
            return RedirectToAction("RequestsList", new { id = cedDoc });
        }

    }
}

Examen2WebApp/Views/Solicitud/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Lista de profesores</h2>
<table>
    <tr style="margin: 2px 0px 2px 0px">
        <th style="width: 100px">Cedula</th>
        <th style="width: 100px">Nombre</th>
        <th style="width: 100px">Apellidos</th>
        <th style="width: 100px">Grado Académico</th>
        <th style="width: 100px">Solicitudes</th>
    </tr>
    @foreach (var docente in ViewBag.docentes)
    {
        <tr style="margin: 2px 0px 2px 0px">
            <td>@docente.Cedula</td>
            <td>@docente.Nombre</td>
            <td>@docente.Apellidos</td>
            <td>@docente.GradoAcademico</td>
            <td>@Html.ActionLink("Ver solicitudes","RequestsList","Solicitud",new { id = docente.Cedula }, null )</td>
        </tr>
    }
</table>

Examen2WebApp/Views/Solicitud/RequestsList.cshtml
@model IEnumerable<Examen2WebApp.Models.Mentoria>
@{
    ViewBag.Title = "RequestsList";
}

<h2>Solicitudes</h2>

<p>Cantidad de solicitudes: @Model.Count()</p> 

@if (Model.Count() != 0)
{
<table>
    <tr style="margin-bottom: 2px">
        <th style="width: 100px">Carne</th>
        <th style="width: 200px; text-overflow: clip">Nombre</th>
        <th style="width: 200px">Área de Mentoria</th>
        <th style="width: 200px">Estado</th>
        <th style="width: 200px">Donación</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="margin-bottom: 2px">
            <td>@item.Estudiante.Carne</td>
            <td>@item.Estudiante.Nombre @item.Estudiante.Apellidos</td>
            <td>@item.AreaDeMentoria.Nombre</td>
            <td>@item.Estado</td>
            @if (item.Donacion == null || item.Donacion == 0)
            {
                <td></td>
            }
            else
            {
                <td>@item.Donacion</td>
            }
            @if (item.Estado != "Aceptada")
            {
                <td>@Html.ActionLink("Aceptar solicitud", "AcceptRequest", "Solicitud", new { cedDoc = item.CedulaDocente, cedEst = item.CedulaEstudiante, areaId = item.AreaDeMentoriaId }, null)</td>
            }
            else
            {
                <td></td>
            }
        </tr>
    }

</table>
}

<div>
    @Html.ActionLink("Lista de Profesores", "Index")
</div>